const int WINDOW_SIZE_X = 800;
const int WINDOW_SIZE_Y = 600;
const int ASTEROID_INITIAL_RADIUS = 50;
const int ASTEROID_SPLIT_NUMBER = 2; //not working
const int DELAY_BETWEEN_BULLETS = 200; 
const int BULLET_LIFESPAN = 500;
const int PLAYER_MOVE_SPEED = 8; //not working
const int PLAYER_LIVES = 3;
const double PLAYER_DECELERATION = .02;
const int BULLET_MOVE_SPEED = 15; 
const double ASTEROID_MAX_SPD = 3.0;
const int DELAY_BETWEEN_LEVELS = 1000;
const int DELAY_BETWEEN_RESPAWNS = 1000;
const int INVULNERABLE_DURATION = 2000;
const double SAFETY_ZONE = 100;
const int POOF_LIFESPAN = 300;