const int WINDOW_SIZE_X = 800;
const int WINDOW_SIZE_Y = 600;
const int ASTEROID_SPLIT_NUMBER = 2;
const int DELAY_BETWEEN_BULLETS = 250; 
const int BULLET_LIFESPAN = 500;
const int PLAYER_MOVE_SPEED = 8; //not working
const double PLAYER_DECELERATION = .02;
const int BULLET_MOVE_SPEED = 15; 
const double MAX_SPD = 1.5;